# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: GRAB
description: GRAB, an R package of methods designed for biobank data
baseurl: "/grab.github.io"
url: "https://wenjianbi.github.io"
repository: GeneticAnalysisinBiobanks/GRAB

permalink: pretty

# Set default layout for pages in docs folder
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"

# Build settings
remote_theme: just-the-docs/just-the-docs
color_scheme: light

# Custom CSS
assets:
  css:
    - "assets/css/custom.css"

# Enable math support via MathJax
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: GFM
  hard_wrap: false

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "GRAB on GitHub":
    - "https://github.com/GeneticAnalysisinBiobanks/GRAB"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Enable or disable the site search
search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# For copy button on code
enable_copy_code_button: true

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - about.markdown
  - setup_files/
  - just-the-docs-main/
  - README.md
